alphagov/govuk-ruby-images

builder.Dockerfile
Publisher requires it. It may as well be in the builder image in case anything else requires it too
=> Install git in builder image

base.Dockerfile
Adding default-libmysqlclient-dev to the base image as its required for few apps.
https://trello.com/c/dwXqpVAi/968-base-and-builder-images-s
=> Adding default-libmysqlclient-dev

base.Dockerfile
Minideb included timezone data, whereas the ubuntu image does not. The data is required for a lot of ruby apps to work, so we should install it in the base image.
=> Include tzdata package in base images

builder.Dockerfile
Some apps need this at the `bundle install` stage.
=> Add libpq-dev (Postgres headers) to builder image.

base.Dockerfile, builder.Dockerfile
Some apps require this - example app is service-manual-publisher
=> libpq-dev is needed in the builder images and libpq5 in the base image.

base.Dockerfile, build.sh, builder.Dockerfile
Apply the `ln -s /tmp /app/tmp` workaround to the base image so we don't have to deal with it multiple times as we add the rest of the publisher apps. Several apps need it because some rubygems assume that `$APP_HOME/tmp` is writeable (and I'm pretty sure it's unsound to just set `$APP_HOME` somewhere other than the root of the app's install path).
See commit messages for other details.
- Dev/test cycle time improvements
- Fail fast when required build args are missing.
- Add a dry-run mode to the build script and make it executable.
- `set -o pipefail` in shell options in the Dockerfile.
- Speed up the OpenSSL build.
- Move build-essential packages to the builder image (also saves ~200 MB from the app image footprint).
- Other minor improvements
- Factor out some env vars from the …
=> Create /app/tmp symlink in base image + minor improvements.

versions/2_7_5
Nothing seems to be using them any more:
https://sourcegraph.com/search?q=govuk-ruby-base:2.7.5
https://sourcegraph.com/search?q=repo:alphagov+file:dockerfile+2.7.5
=> Stop building Ruby 2.7.5 images.

base.Dockerfile, with_tmpdir_for_ruby.sh
- Copy the wrapper script into place after the env var that specifies its destination has been set.
- Abort on undefined shell variables (`set -u`), which would have caught the above.
- Fix a bug where the script would re-exec itself instead of the wrapped command.
- Instead of forking, just `exec` the wrapped command. This makes the script fail more predictably if you pass a shell builtin (like `set` or `echo`) as the command, and saves having a useless shell process hanging around for the lifetime of the server process.
- `BUNDLE_BIN` isn't populated at base image build time (d'oh).
- Add a smoke test for the wrapper script. This would have caught the above bug in the wrapper script.
* Did a bunch of manual testing with `DRY_RUN=1 ./build.sh 2_7 && docker run -it --rm -u1000 …
=> Fix the with_tmpdir_for_ruby wrappers (again).

builder.Dockerfile
Seems it's needed in order to build Nokogiri. Fixes d07c6af.
Kudos to @gclssvglx for spotting this.
=> Add `xz` (compression tool) to the builder images.

.github/workflows/build.yaml
Fixes a bug that I introduced in 7e874e7 (oops 🤦) where we'd default to `DRY_RUN=1` when the build is triggered by anything other than `workflow_dispatch` (i.e. on-demand builds).
=> Fix pushing to registry on scheduled builds.

base.Dockerfile
This saves on copypasta (and therefore maintenance burden) in app Dockerfiles.
=> Add Amazon RDS TLS cert bundle to base image.

base.Dockerfile
Back out the `pkg-config` package, since this breaks cross-compilation and this was causing builds to fail on GitHub Actions (but not local `docker build`).
Also revert to OpenSSL 1.1.1 for all Ruby versions, as it turns out the `openssl` rubygem [doesn't fully support OpenSSL 3 yet](https://www.github.com/ruby/openssl/issues/369). It works, but not all of its tests are passing and the compiler emits a ton of warnings about deprecated APIs and discarded `const`ness.
Partially reverts #36.
Tested: builds succeed [on GitHub Actions](https://github.com/alphagov/govuk-ruby-images/actions/runs/3941536687) as well as Docker Desktop. [Whitehall builds successfully on the new image](https://github.com/alphagov/whitehall/actions/runs/3941789850) and works on the integration cluster.
=> Fix build on GitHub and revert to OpenSSL 1.1.1.

base.Dockerfile
This makes it easy to switch back to glibc malloc without rebuilding, e.g. for future benchmarking or comparison if there's any suspicion of a problem. As a bonus, we also cover other processes `exec`ed by Ruby, rather than just Ruby itself.
While we're there, avoid unnecessarily installing the `libssl-dev` package, which we weren't using.
=> Enable jemalloc via `LD_PRELOAD` instead of `--with-jemalloc`.

base.Dockerfile
Fixes `object cannot be preloaded` warnings from `ld.so` during build.
No functional change.
=> Don't set `LD_PRELOAD` until jemalloc is installed.

.github/workflows/lint.yaml
[Release notes](https://www.github.com/ludeeus/action-shellcheck/releases/tag/2.0.0)
=> Update action-shellcheck from 1.1.0 to 2.0.0.

README.md
This is a potential gotcha vs [docker-library/ruby](https://github.com/docker-library/ruby).
=> Mention the `$APP/tmp` workaround in the README.

builder.Dockerfile
The `psych` gem needs to compile against libyaml.
Not sure why we're only running into this now — maybe Rails was happy with our stock version of `psych` until recently? — but in any case it seems sensible to include headers in the builder image for libraries that we ship in our base image.
=> Add libyaml headers to builder image.

builder.Dockerfile
We're not using any of these yet, but it makes sense to ship headers in the builder image for all the libraries that we include in the base image. Should reduce the chance of being caught out next time some dependency starts requiring a native rubygem that depends on any of those libs.
=> Add remaining missing headers to builder image.

base.Dockerfile
Only Router API uses this AFAICT. At some point we'll have to switch its RDS instance to use the new CA and then it'll need the new roots.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL
=> Add new RDS CA root/intermediate certs.

base.Dockerfile
Yarn 1.22.20 and 1.22.21 (current) have a nasty regression which breaks `yarn install --immutable` for at least [alphagov/frontend](https://github.com/alphagov/frontend/pull/3859).
=> Pin Yarn to 1.22.19.

builder.Dockerfile
Saves every consumer having to update their Dockerfile when they encounter this.
https://guides.rubyonrails.org/asset_pipeline.html#local-precompilation
=> Prevent secret_key_base from breaking assets:precompile.

.github/workflows/build-multiarch.yaml, .github/workflows/build.yaml, .github/workflows/sign.yaml
So we previously merged-in the new multi-architecture build job, but it is currently does not trigger on main. This should switch things around so that we are now using the multi-arch builds job by default.
I'm hoping the image signing job will continue to work as-is.
* https://github.com/alphagov/govuk-ruby-images/pull/68
=> Make multi-arch builds the default now.

.github/workflows/build-multiarch.yaml
As we do a checksum.... check when pulling Ruby, the build failed because The ARM build matrix still contains 3.2.2 rather than 3.2.3.
=> This matrix was missed when bumping Ruby 3.2

.github/workflows/build-multiarch.yaml
Turns out there's _three_ matrixes with the same information.
It's a shame that Github doesn't give us an easy way to address this by reusing a single matrix across multiple jobs, huh?
...or maybe there is?
=> Correct another matrix - we missed another one!

base.Dockerfile
I'm having a hard time reproducing this issue but some of our developer teams seem to have run into it, so let's just try the workaround.
https://bugs.ruby-lang.org/issues/20085
=> Work around inconsistent -mbranch-protection in Ruby 3.3.0.

.github/workflows/build-multiarch.yaml, build-matrix.json
This reduces the number of jobs we have in the workflow files by adding another matrix "dimension". This should give us AMD64 and ARM64 builds for each Ruby version specified in the JSON file.
=> Refactor Jobs - Consolidate Arches w/ Matrix

.github/workflows/build-multiarch.yaml
With the "improvements" to the main job matrix, we are now running the Manifest job more times than necessary.
This change should adjust the Manifest matrix so it only runs once per version, rather than twice.
=> Stop Manifest Job running more times than needed

.github/workflows/build-multiarch.yaml
This PR tweaks the Multi-arch build flow to temporarily store the Image Digests and pass them to a "Combine" job that uses `docker buildx imagetools` instead of us trying to use the `manifest` command ourselves. This follows a pattern used in Docker's own [documentation](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners).
In earlier iterations, we were manually creating the Docker Manifest ourselves by trying to cobble together architecture-specific tags and then manually using the `manifest` command to try and build and push a manifest, which is something that shouldn't be necessary (nor a good idea) when Docker has the capability to automatically select the correct architecture.
This is something we were doing because `docker buildx …
=> Use Docker Imagetools to Create Docker Manifest

.github/workflows/build-multiarch.yaml
We're getting a somewhat cryptic error message:
```
buildx failed with: ERROR: failed to solve: failed to push ghcr.io/alphagov/govuk-ruby-base:3.3.0: can't push tagged ref ghcr.io/alphagov/govuk-ruby-base:3.3.0 by digest
```
I'm not sure if this is because it is already trying to push the image with a tag before it has consolidated the different architecture images from across the different builds. But let's see if it's because `push-by-digest` doesn't replace/override the `push` option (these options appear to be poorly documented)
=> Try to fix the digest error.

.github/workflows/build-multiarch.yaml, build-matrix.json, builder.Dockerfile, install_packages.sh
This updates the Ruby Image builder to try and use the ARM runners (from the Github ARM Runners Beta). I've tweaked the strategy matrix to hopefully select the correct runner via the `runs-on` option.
=> Re-wire the multiarch build to use ARM runners.

build-matrix.json
This bumps the base Ruby versions to 3.2.4 and 3.3.1 in order to address [CVE-2024-27282](https://www.ruby-lang.org/en/news/2024/04/23/arbitrary-memory-address-read-regexp-cve-2024-27282/), in particular, concerning an arbitrary memory address read vulnerability with RegEx search.
This should also fix a bug in 3.3.0 that needed a workaround for builds to pass.
=> Bump to Ruby 3.2.4 and 3.3.1 to address CVE

LICENCE, README.md
The README had gotten pretty out of date with recent improvements to the way we're configuring the builds.
Fix the instructions and give the rest of the doc an editorial sprucing up.
[Preview](https://github.com/alphagov/govuk-ruby-images/blob/sengi/readme/README.md)
=> Update README to reflect the new build config.

base.Dockerfile, build-matrix.json
This bumps two different things:
- Ruby 3.3.3 (up from Ruby 3.3.1)
- Ubuntu 24.04 LTS (up from Ubuntu 22.04 LTS)
As far as I can tell, there isn't a reason why we are stuck on Ubuntu 22.04 - this just keeps us on the latest LTS version of the OS.
=> Ruby 3.3.3 and Ubuntu 24.04 LTS

base.Dockerfile, builder.Dockerfile
Only publishing-api strictly needs this right now, but it's a small library so adding it here is reasonable. Saves having to pull down the Apt catalog in the pubapi build, and reduces the chance of copypasta/cargo-culting extra steps from the pubapi Dockerfile.
See https://github.com/alphagov/publishing-api/pull/2788.
=> Add libjsonnet++ for publishing-api Content Schemas.

.github/workflows/build-multiarch.yaml, README.md, build.sh
We recently encountered a problem (#96) where a downstream repo was unwittingly pinning an image tag for an obsolete Ruby patch version (which we've never supported, but this wasn't very clear to app dev teams) and removing the unwanted pin uncovered other brokenness that was being masked by remaining on the obsolete builder image.
Explicitly remove support for obsolete Ruby patch versions so that other feature teams can't repeat the same mistake.
For security reasons we should never be running an old Ruby patch version; we'd always either fix forward (like we did with https://bugs.ruby-lang.org/issues/20085) or temporarily pin Ruby within govuk-ruby-images until upstream releases a fix. There's no valid reason for app teams to specify an old patch version.
There are currently no …
=> Remove support for pinning obsolete Ruby versions.

.github/workflows/build-multiarch.yaml, build-matrix.json
We no longer need to install Docker ourselves now that https://github.com/actions/partner-runner-images/tree/main/images are available.
Should speed up builds somewhat.
Tested: https://github.com/alphagov/govuk-ruby-images/actions/runs/9697782700/job/26762749352
=> Use preinstalled Docker from the runner image.

.github/workflows/gc.yaml
We're hosting hundreds of old, obsolete package (image) binaries.
Keep all tags, such as `3.3`, `3.3-foobar1` etc. and the most recent 10 untagged images for each package (base, builder). Delete the rest on a weekly schedule.
=> Garbage-collect old, untagged packages.

.github/workflows/gc.yaml
The [delete-package-versions docs](https://github.com/actions/delete-package-versions/blob/-/README.md) don't mention it, but it fails without `packages: write`.
Indeed [their test](https://github.com/actions/delete-package-versions/blob/063586/.github/workflows/test.yml#L10) has it.
=> Grant packages.write to image GC job.

.github/workflows/gc.yaml
Keep all images with a [supported tag](https://github.com/alphagov/govuk-ruby-images/blob/-/build-matrix.json#L2) and delete the rest except for 10 most recent unsupported-tagged images per {base, builder}.
Also keep a few more untagged packages around just so we can be sure we're not throwing away the attestations for images that haven't yet themselves been GCed. (Doesn't actually matter right now cos we're not actually doing anything with the signatures, just avoiding a potential future footshooter.)
Tested: https://github.com/alphagov/govuk-ruby-images/actions/runs/9713340782/job/26809922090#step:3:6
=> Garbage-collect old, tagged-but-unsupported images.

build-matrix.json
This bumps Ruby to 3.2.5 and 3.3.4 respectively - these releases address some bugs. In particular, [the 3.3.4 update](https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/) addresses a bug that has affected us when trying to `bundle install` the `net-pop` package.
=> Bump Ruby to 3.2.5 and 3.3.4

.github/workflows/build-multiarch.yaml
This adds the full Ruby Semantic Version to the list of image tags. This will allow apps to manually update their Ruby version, should they choose, however, this comes with a warning...
> [!WARNING]
> **Even though we are making these tags an option, using them is not recommended in most cases**.  
> If you decide to use the full semantic tags for your base images, you could miss out on Security updates or bug fixes.
This also tries to add the labels/annotations to the image manifest - this info currently seems to be missing from our images.
* Fixes #107
=> Add full SemVer tags to Ruby Base Images

.github/workflows/build-multiarch.yaml
I am going to "throw in the towel" on annotations for now - it's getting too difficult to figure out why a `jq` expression works in an expression editor, then fails in a bash terminal, and then fails again once it's been fixed for the bash terminal when run again in a Workflow.
=> Disable Annotations for now

build-matrix.json
This updates the GOV.UK Ruby Base images to Ruby 3.3.5, released 3rd September 2024.
[This update brings mainly bug fixes](https://github.com/ruby/ruby/releases/tag/v3_3_5) - no obvious CVEs this time.
=> Update to Ruby 3.3.5

build-matrix.json
This updates the Ruby Base Images to the following versions:
* Ruby 3.2.6
* Ruby 3.3.6
Both releases predominantly focus on bug fixes.
=> Update Base Images to Ruby 3.2.6 and 3.3.6

build-matrix.json
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-1-released/
=> Correct checksum for Ruby 3.4.1

build-matrix.json
This updates:
- the 3.4 branch to [3.4.2]
- the 3.3 branch to [3.3.7]
- the 3.2 branch to [3.2.7]
All of these are routine/bugfix releases.
[3.4.2]: https://ruby-lang.org/en/news/2025/02/14/ruby-3-4-2-released/
[3.3.7]: https://ruby-lang.org/en/news/2025/01/15/ruby-3-3-7-released/
[3.2.7]: https://ruby-lang.org/en/news/2025/02/04/ruby-3-2-7-released/
=> Update Ruby versions to latest available

build-matrix.json
These versions were released in the last 6 weeks.
Motivation for this change: We've updated GOV.UK Chat to Ruby 3.4.3 and are now unable to deploy, it seemed that updating the platform would be a better exercise than downgrading the app.
=> Update to 3.2.8, 3.3.8 and 3.4.3 Ruby releases

build-matrix.json
This upgrades Ruby Base Images to use the following versions:
* 3.2.9
* 3.3.9
* 3.4.5
These release includes the following security fixes:
* [CVE-2025-24294: Possible Denial of Service in resolv gem](https://www.ruby-lang.org/en/news/2025/07/08/dos-resolv-cve-2025-24294/)
* [CVE-2025-43857: DoS vulnerability in net-imap](https://www.ruby-lang.org/en/news/2025/04/28/dos-net-imap-cve-2025-43857/)
=> Update Ruby versions to 3.2.9, 3.3.9, and 3.4.5

.github/workflows/actionlint.yaml, .github/workflows/build-multiarch.yaml, .github/workflows/gc.yaml, .github/workflows/lint.yaml, .github/workflows/sign.yaml
We agree that pinning the versions of GitHub Actions actions to a commit hash
instead of a mutable tag is the correct choice.
We have a lot of places where we use them. The changes in this commit were
generated by using a tool called pinact[1] which can convert pinned tags in GHA
workflows to the commit hash they point to at that moment in time.
To generate the change set I ran `pinact run` from the root of the repository.
[1] https://github.com/suzuki-shunsuke/pinact
=> Globally pin GitHub Actions actions to commit hashes not tags

.github/workflows/sign.yaml
So that it uses the same version as other repositories
=> Udate the aws-actions/configure-aws-credentials action
